---
sudo: false

language: node_js

node_js:
	- node
	- 4
	- 6

cache:
	directories:
		- node_modules

before_install:
	- npm config set spin false

install:
	- npm install -g codecov
	- npm install -g bithound

script:
# testing provided by coverage
#  - npm test
	- npm run lint
	- npm run coverage
	- bithound check git@github.com:maxkoryukov/passport-wix-app.git

after_success:
	- codecov
...
