---
sudo: false

language: node_js

node_js:
  - 4
  - 6
  - 7

matrix:
  fast_finish: true
  allow_failures:
  - node_js: 8

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install
  - npm install -g codecov
  - npm install -g bithound

script:
  - npm run lint
  - npm test
  - npm run coverage
  - codecov
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git

# after_success:
...
